apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-storage
spec:
  storageClassName: azurefile-csi  # Azure Files, not Blob as discussed with OIM
  accessModes:
  - ReadWriteMany  # In case of scaling asset-server
  resources:
    requests:
      storage: 5Gi