apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-storage
spec:
  storageClassName: managed-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Conservative for UAT testing
