apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-storage
spec:
  storageClassName: azurefile-csi-static
  accessModes:
  - ReadWriteMany
  volumeName: asset-storage-uat-pv
  resources:
    requests:
      storage: 5Gi