apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: specify-storage
spec:
  storageClassName: managed-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Conservative for UAT testing
