apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: specify-storage
spec:
  storageClassName: local-path  # K3d's default storage class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
